language: python
sudo: false
python:
  - "2.7"
  - "3.4"
  - "3.6"
  - "3.7"
env:
  - TEST_MODE=tests
install: |
  pip install tdparser && \
  [ coverage != $TEST_MODE ] || pip install codecov && \
  [ flake8 != $TEST_MODE ] || pip install flake8
script: |
  if [ coverage = $TEST_MODE ]; then
    coverage run --source=file_archive --branch tests/__main__.py && \
    codecov
  elif [ flake8 = $TEST_MODE ]; then
    flake8 file_archive tests
  else
    python tests
  fi
matrix:
  include:
    - python: "2.7"
      env: TEST_MODE=coverage
    - python: "2.7"
      env: TEST_MODE=flake8
