# https://ci.appveyor.com/project/remram44/rpaths
build: false
shallow_clone: true
environment:
  matrix:
    - PYTHON: "C:/Python27"
    - PYTHON: "C:/Python34"
install:
  - set PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%
  - pip install -U setuptools pip
  - pip install tdparser
  - python setup.py install
test_script:
  - python tests
